{{- if .Values.global.cp.resources.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.cp.resources.serviceaccount.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
