# Copyright (c) 2023 Cloud Software Group, Inc. All Rights Reserved. Confidential and Proprietary.

{{-  $emsParams := include "need.msg.ems.params" . | fromYaml -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $emsParams.ems.name }}-scripts
  namespace: "{{ .Release.Namespace }}"
  labels:
    tib-dp-app: msg-ems-ftl
    tib-msg-stsname: "{{ $emsParams.ems.name }}-ems"
    {{ include "msg.dp.labels" . | indent 4 }}
data:
  emsParams: |
{{ include "need.msg.ems.params" . | indent 4 }}

# 
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
...
