# Resources
# https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

# no of replicas
replicaCount: "1"

image:
  registry: ""
  repository: /stratosphere/tp-provisioner-agent
  pullPolicy: Always

nodeSelector:
  kubernetes.io/os: linux

affinity: {}

tolerations: {}

enableIngress: true
ingress:
  annotations: {}
    # nginx custom annotation example
    #nginx.org/rewrites: "serviceName={{ include \"tp-provisioner-agent.consts.appName\" . }} rewrite=/" #https://github.com/nginxinc/kubernetes-ingress/tree/v2.4.2/examples/ingress-resources/rewrites
  pathPrefix: /tibco/provisioner-agent/
  className: "haproxy-dp-{{ .Values.global.tibcoDataPlaneId}}"  # Ex: nginx, haproxy

global:
  tibcoDataPlaneId: "abcd"
  subscriptionId: "sub1"
  dockerRegistry: reldocker.tibco.com