apiVersion: v2
name: tp-provisioner-agent
version: 1.0.0
appVersion: 1.0.0
description: TIBCO Data Plane -- Provisioner Agent
home: https://github.com/tibco/tp-core-provisioner-agent
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
  - name: TIBCO CIC Compute Dev Team
    email: compute-dev@tibco.com 
keywords:
  - provisioner-agent
  - data-plane
