apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    {{- include "bwprovisioner.labels" . | nindent 4 }}
  name: {{ include "bwprovisioner.fullname" . }}-serviceconfig
data:
  {{- range $filename, $content :=  .Values.config }}
  {{- if $content }}
  {{ $filename }}: {{ tpl $content $ | quote }}
  {{- end }}
  {{- end }}
