apiVersion: cloud.tibco.com/v1
kind: TibcoAlb
metadata:
  name: traefik-ingress-external
  namespace: traefik-system
spec:
  profileName: lb-external
  endpoint:
    healthCheckSetting:
      checkConfig:
        healthyThreshold: 2
        interval: 20
        timeout: 5
        unhealthyThreshold: 2
      healthCheckPath: /ping
      healthCheckPort: 9000
      healthCheckSuccessCodes: "404"
    lbPort: 443
    lbProtocol: HTTPS
    path: /*
    targetPort: 8443
    targetProtocol: HTTPS
  serviceName: {{ .Release.Name }}-traefik

---

apiVersion: cloud.tibco.com/v1
kind: TibcoDns
metadata:
  name: traefik-ingress-external
  namespace: traefik-system
spec:
  dns:
    domain: {{ .Values.domain.external }}
    vanityDomain: "*"
  values:
    crRef:
      crKind: tibcoalb
      name: traefik-ingress-external
      namespace: traefik-system
