{{- if .Values.awsRole1.enable -}}
apiVersion: cloud.tibco.com/v1
kind: TibcoRole
metadata:
  name: {{ .Values.awsRole1.name }}
  namespace: {{ .Values.awsRole1.namespace }}
spec:
  outputConfigMap:
    name: {{ .Values.awsRole1.name }}
    roleArnKey: roleArn
  awsRole:
    name: {{ .Values.awsRole1.iamName }}
    {{- with .Values.awsRole1.tags}}
    tags:
      {{- toYaml . | nindent 6}}
    {{- end }}
    trustRelationship: |
      Version: '2008-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Federated: "{{ .Values.global.oidc_provider_arn }}"
        Action: sts:AssumeRoleWithWebIdentity
        Condition:
          StringEquals:
            "{{ .Values.global.oidc_issuer_hostpath }}:sub": "system:serviceaccount:{{ .Values.awsRole1.saNamespace}}:{{ .Values.awsRole1.saName}}"
    inlinePolicies:
      {{- .Values.awsRole1.inlinePolicies | toYaml | nindent 6}}

{{- end -}}
