apiVersion: v2
name: dp-config-es
version: "1.0.3"
appVersion: "1.0.0"
description: dp-config-es
type: application
home: https://github.com/tibco/cicinfra-integration
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
