receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
processors:
  k8sattributes:
    filter:
      namespace: {{ .Values.global.cp.namespace }}
exporters:
  otlp/elastic:
    endpoint: "{{ .Values.tibotelcollectorfinops.apmEndpoint }}" # ELASTIC_APM_ENDPOINT
    headers:
      Authorization: "Bearer {{ .Values.tibotelcollectorfinops.apmToken }}"
    tls:
      insecure: false
      insecure_skip_verify: true
extensions:
  health_check:
  memory_ballast:
service:
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    metrics:
      exporters:
        - otlp/elastic
      processors:
        - k8sattributes
      receivers:
        - prometheus
