receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318
#  fluentforward:
#    endpoint: 0.0.0.0:8006
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
#  k8s_events:
#    auth_type: kubeConfig
##   namespaces: ["otel-system, elastic-system"]
#    namespaces: [{{ .Values.tibotelcollectornops.namespacesList }}]
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch: {}
exporters:
  logging: {}
extensions:
  health_check:
  memory_ballast:
service:
  telemetry:
    logs: {}
    metrics:
      address: :8888
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    logs:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
        - prometheus
    traces:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp