receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318
processors:
  k8sattributes:
    filter:
      namespace: {{ .Values.global.cp.namespace }}
exporters:
  logging: {}
  otlp/elastic:
    endpoint: "{{ .Values.tibotelcollectorsvc.apmEndpoint }}" # ELASTIC_APM_ENDPOINT
    headers:
      Authorization: "Bearer {{ .Values.tibotelcollectorsvc.apmToken }}"
    tls:
      insecure: false
      insecure_skip_verify: true
  elasticsearch/log:
    endpoints: [{{ .Values.tibotelcollectorsvc.esEndpoint }}]
    logs_index: {{ .Values.tibotelcollectorsvc.esLogIndex }}
    user: {{ .Values.tibotelcollectorsvc.esUserName }}
    password: {{ .Values.tibotelcollectorsvc.esPassword }}
    retry:
      enabled: false
    tls:
      insecure: false
      insecure_skip_verify: true
  elasticsearch/trace:
    endpoints: [{{ .Values.tibotelcollectorsvc.esEndpoint }}]
    logs_index: {{ .Values.tibotelcollectorsvc.esTraceIndex }}
    user: {{ .Values.tibotelcollectorsvc.esUserName }}
    password: {{ .Values.tibotelcollectorsvc.esPassword }}
    retry:
      enabled: false
    tls:
      insecure: false
      insecure_skip_verify: true
extensions:
  health_check:
  memory_ballast:
service:
  telemetry:
    logs: {}
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    logs:
      exporters:
        - logging
        - elasticsearch/log
      processors:
        - k8sattributes
      receivers:
        - otlp
    traces:
      exporters:
        - logging
        - otlp/elastic
      processors:
        - k8sattributes
      receivers:
        - otlp