{{/*custom network policy crafted for DataPlane usecase.*/}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "haproxy-ingress.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
spec:
    podSelector:
        matchLabels:
            {{- include "haproxy-ingress.selectorLabels" . | nindent 12 }}
    policyTypes:
        - Ingress
        - Egress
    ingress:
      - from:
          - namespaceSelector: {}
            podSelector:
              matchLabels:
                component: kube-apiserver
        ports:
          - protocol: TCP
            port: webhook
      - from:
          - namespaceSelector: {}
            podSelector:
              matchLabels:
                app.kubernetes.io/component: tibco-platform-data-plane      
    egress:
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0

