apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "o11y-service.consts.appName" . }}
  labels:
    {{- include "o11y-service.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "o11y-service.shared.labels.selector" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "o11y-service.shared.labels.standard" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: {{ .Values.global.cp.containerRegistry.secret }}
      {{- if .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      serviceAccountName: {{ .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      {{- else }}
      serviceAccountName: {{ include "o11y-service.sa" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: tp-o11y-service
          image: {{ .Values.global.cp.containerRegistry.url }}/piap/o11y-service:{{ .Values.global.o11yservice.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 8003
              name: tp-o11yservice
          env:
            - name: IS_CP
              value: "false"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: o11y-cfgs
              readOnly: true
              mountPath: "/o11y/cfgs"
            - name: o11y-secrets
              readOnly: true
              mountPath: "/o11y/secrets"
      volumes:
        - name: o11y-cfgs
          configMap:
            name: {{ include "o11y-service.fullname" . }}
        - name: o11y-secrets
          secret:
            secretName: {{ include "o11y-service.fullname" . }}