apiVersion: v1
kind: Service
metadata:
  name: {{ include "o11y-service.consts.appName" . }}
  labels:
    {{- include "o11y-service.shared.labels.standard" . | nindent 4 }}
spec:
  ports:
    - name: server
      port: 8113
      protocol: TCP
      targetPort: 8113
  selector:
    {{- include "o11y-service.shared.labels.selector" . | nindent 4 }}
