apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: 8.5.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    service:
      spec:
        type: ClusterIP
