apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.kibana.version }}
  count: {{ .Values.kibana.count }}
  config:
    # Configure this to a domain you control
    server.publicBaseUrl: https://kibana.{{ .Values.domain }}
    xpack.security.sameSiteCookies: None
  elasticsearchRef:
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
  http:
    service:
      spec:
        type: ClusterIP
