apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: 8.5.0
  count: 1
  elasticsearchRef:
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
  http:
    service:
      spec:
        type: ClusterIP
