kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name }}-kibana
  namespace: {{ .Release.Namespace }}
  annotations:
     traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: {{ .Values.kibana.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.kibana.ingress.host }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.kibana.ingress.service }}
                port:
                  name: https
